// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mode": string;
      "githubToken": string;
      "githubRepo": string;
      "githubBranch": string;
      "githubContentPath": string;
      "supabaseUrl": string;
      "supabaseKey": string;
      "supabaseTable": string;
      "shareBaseUrl": string;
      "copyShareUrl": boolean;
      "includeNotes": boolean;
      "statusField": string;
    };
  }
}
